default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: password

development:
  <<: *default
  database: shop_dev

test:
  <<: *default
  database: shop_test

production:
  <<: *default

